on:
  push:
    branches:
      - main
      - reportWriting
permissions:
  contents: write

jobs:
  Doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Action Doxygen and GitHub Pages
        id: ghaction
        uses: AgarwalSaurav/ghaction-doxygen-ghpages@v2.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: .
          doxyfile-path: docs/Doxyfile
          html-output-folder: docs/html
          branch: gh-pages

  buildReport:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: report
          root_file: report.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Report
          path: report/report.pdf
